CREATE TABLE [stg].[LYTY_TRANSACCION] (
  [CODIGODEPARTICIPANTE] [varchar](4) NOT NULL,
  [CODIGODELOCAL] [varchar](4) NOT NULL,
  [NUMTARJETABONUS] [varchar](19) NOT NULL,
  [FECHATRANSACCION_CAB] [varchar](8) NOT NULL,
  [HORATRANSACCION_CAB] [varchar](8) NOT NULL,
  [HORATRANSSECCION_CAB] [varchar](6) NOT NULL,
  [NROPOS] [varchar](6) NOT NULL,
  [NROTRNPOS] [varchar](6) NOT NULL,
  [MONTOTOTAL] [varchar](15) NULL,
  [SIGNO_MT] [varchar](1) NULL,
  [MONTOTOTALNUM] [float] NULL,
  [PTOSACUMULADOS] [varchar](15) NULL,
  [SIGNO_PA] [varchar](1) NULL,
  [PTOSACUMULADOSNUM] [float] NULL,
  [FECHAASIGNACION_CAB] [varchar](8) NULL,
  [CODIGODEPROMOCION] [varchar](7) NOT NULL,
  [DESCRIPCION_PRM] [varchar](50) NULL,
  [FECHACARGAINICIAL_PRM] [varchar](8) NULL,
  [FECHACARGAULTMODIF_PRM] [varchar](8) NULL,
  [TIPODETRANSACCION] [varchar](10) NULL,
  [NOMBREDEALER] [varchar](50) NULL,
  [FECHACARGAINICIAL_CAB] [varchar](8) NULL,
  [FECHACARGAULTMODIF_CAB] [varchar](8) NULL,
  [IDTRX] [varchar](18) NOT NULL,
  [SEC] [varchar](3) NOT NULL,
  [PLU] [varchar](14) NOT NULL,
  [CANTIDAD] [varchar](9) NULL,
  [CANTIDADNUM] [float] NULL,
  [MONTOPARCIAL] [varchar](15) NULL,
  [SIGNO_MP] [varchar](1) NULL,
  [MONTOPARCIALNUM] [float] NULL,
  [FECHACARGAINICIAL_DET] [varchar](8) NULL,
  [FECHACARGAULTMODIF_DET] [varchar](8) NULL,
  [date] [varchar](8) NULL,
  [hora] [varchar](8) NULL
)
ON [PRIMARY]
GO